name: Firmware build

on:
  push:
    branches: [ wasm ]
  pull_request:
    branches: [ wasm ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

permissions:
  contents: read

jobs:

  # normal builds
  build_main:
    runs-on: ubuntu-20.04
    strategy:
      # devices to build for
      matrix:
        board: [EMSCRIPTEN2]
      # try and build for all devices even if one fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.31
        actions-cache-folder: 'emsdk'
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        BOARD: ${{ matrix.board }}
      run: |
        make
    - name: Upload ${{ matrix.board }} build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.board }}
        path: |
          bin/*.wasm
